/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistaPrincipal;

import bo.RecuperaDatosReportesBO;
import java.awt.Dimension;
import java.awt.GridLayout;
import org.jfree.chart.ChartPanel;
import reportes.Grafico;

/**
 *
 * @author Kevscl
 */
public class principalGrafico extends javax.swing.JPanel {

    RecuperaDatosReportesBO rbo = new RecuperaDatosReportesBO();

    public principalGrafico() {
        initComponents();
        graficos();
        iniciaDatos();
    }

    public void iniciaDatos() {
        int pro = rbo.obtenerNumeroTiposDeProductos();
        float tven = rbo.obtenerTotalVentas();
        int nven = rbo.obtenerNumeroVentas();
        float tcom = rbo.obtenerTotalCompras();
        int pend = rbo.obtenerNumeroPagosPendientes();
        float gan = tven-tcom;
        
        labelProductos.setText(pro+"");
        labelTotalVentas.setText("$"+tven);
        labelNuVentas.setText(nven+"");
        labelCompras.setText("$"+tcom);
        labelPagos.setText(pend+"");
        labelGanancias.setText("$"+gan);
    }

    public void graficos() {
        Grafico g = new Grafico();

        // Gráfico de Productos más Vendidos
        ChartPanel chartPanelProductosMasVendidos = g.ProductosMasVendidos();
        // ChartPanel se ajustará automáticamente al tamaño del JPanel
        int ancho = panelProductosMasVendidos.getWidth();
        int alto = panelProductosMasVendidos.getHeight();
        chartPanelProductosMasVendidos.setPreferredSize(new Dimension(ancho, alto));
        panelProductosMasVendidos.setLayout(new GridLayout(1, 1));
        panelProductosMasVendidos.add(chartPanelProductosMasVendidos);

        // Gráfico de Productos en Stock Mínimo
        ChartPanel chartPanelStockMinimo = g.ProductosEnStockMinimo();
        // ChartPanel se ajustará automáticamente al tamaño del JPanel
        chartPanelStockMinimo.setPreferredSize(new Dimension(ancho, alto));
        int anchow = panelStockMinimo.getWidth();
        int altow = panelStockMinimo.getHeight();
        panelStockMinimo.setLayout(new GridLayout(1, 1));
        panelStockMinimo.add(chartPanelStockMinimo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        rSPanelBorderGradient1 = new RSMaterialComponent.RSPanelBorderGradient();
        rSPanelImage3 = new rojeru_san.rspanel.RSPanelImage();
        lblCaja4 = new javax.swing.JLabel();
        labelIcon = new RSMaterialComponent.RSLabelIcon();
        labelProductos = new javax.swing.JLabel();
        rSPanelBorderGradient2 = new RSMaterialComponent.RSPanelBorderGradient();
        rSPanelImage4 = new rojeru_san.rspanel.RSPanelImage();
        lblCaja5 = new javax.swing.JLabel();
        rSLabelIcon1 = new RSMaterialComponent.RSLabelIcon();
        labelTotalVentas = new javax.swing.JLabel();
        rSPanelBorderGradient3 = new RSMaterialComponent.RSPanelBorderGradient();
        rSPanelImage5 = new rojeru_san.rspanel.RSPanelImage();
        lblCaja6 = new javax.swing.JLabel();
        rSLabelIcon2 = new RSMaterialComponent.RSLabelIcon();
        labelNuVentas = new javax.swing.JLabel();
        rSPanelBorderGradient6 = new RSMaterialComponent.RSPanelBorderGradient();
        rSPanelImage7 = new rojeru_san.rspanel.RSPanelImage();
        lblCaja7 = new javax.swing.JLabel();
        rSLabelIcon3 = new RSMaterialComponent.RSLabelIcon();
        labelCompras = new javax.swing.JLabel();
        rSPanelBorderGradient7 = new RSMaterialComponent.RSPanelBorderGradient();
        rSPanelImage8 = new rojeru_san.rspanel.RSPanelImage();
        lblCaja8 = new javax.swing.JLabel();
        rSLabelIcon4 = new RSMaterialComponent.RSLabelIcon();
        labelPagos = new javax.swing.JLabel();
        rSPanelBorderGradient8 = new RSMaterialComponent.RSPanelBorderGradient();
        rSPanelImage9 = new rojeru_san.rspanel.RSPanelImage();
        lblCaja9 = new javax.swing.JLabel();
        rSLabelIcon5 = new RSMaterialComponent.RSLabelIcon();
        labelGanancias = new javax.swing.JLabel();
        panelStockMinimo = new javax.swing.JPanel();
        panelProductosMasVendidos = new javax.swing.JPanel();

        setLayout(new java.awt.GridLayout(1, 0));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        rSPanelBorderGradient1.setForeground(new java.awt.Color(255, 255, 255));
        rSPanelBorderGradient1.setBorderBottom(false);
        rSPanelBorderGradient1.setBorderLeft(false);
        rSPanelBorderGradient1.setBorderRight(false);
        rSPanelBorderGradient1.setBorderTop(false);
        rSPanelBorderGradient1.setColorPrimario(new java.awt.Color(255, 255, 255));
        rSPanelBorderGradient1.setColorSecundario(new java.awt.Color(255, 255, 255));

        rSPanelImage3.setImagen(new javax.swing.ImageIcon(getClass().getResource("/imgBotones/lblBanner1.png"))); // NOI18N

        lblCaja4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCaja4.setForeground(new java.awt.Color(51, 51, 51));
        lblCaja4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCaja4.setText("PRODUCTOS");

        labelIcon.setForeground(new java.awt.Color(255, 255, 255));
        labelIcon.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.LIBRARY_BOOKS);

        labelProductos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelProductos.setForeground(new java.awt.Color(51, 51, 51));
        labelProductos.setText("0.00");

        javax.swing.GroupLayout rSPanelImage3Layout = new javax.swing.GroupLayout(rSPanelImage3);
        rSPanelImage3.setLayout(rSPanelImage3Layout);
        rSPanelImage3Layout.setHorizontalGroup(
            rSPanelImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelImage3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(labelIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(275, Short.MAX_VALUE))
            .addGroup(rSPanelImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(rSPanelImage3Layout.createSequentialGroup()
                    .addGap(84, 84, 84)
                    .addComponent(lblCaja4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(105, Short.MAX_VALUE)))
            .addGroup(rSPanelImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rSPanelImage3Layout.createSequentialGroup()
                    .addContainerGap(241, Short.MAX_VALUE)
                    .addComponent(labelProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        rSPanelImage3Layout.setVerticalGroup(
            rSPanelImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rSPanelImage3Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(labelIcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(rSPanelImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(rSPanelImage3Layout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addComponent(lblCaja4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(18, 18, 18)))
            .addGroup(rSPanelImage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(rSPanelImage3Layout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addComponent(labelProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(18, 18, 18)))
        );

        javax.swing.GroupLayout rSPanelBorderGradient1Layout = new javax.swing.GroupLayout(rSPanelBorderGradient1);
        rSPanelBorderGradient1.setLayout(rSPanelBorderGradient1Layout);
        rSPanelBorderGradient1Layout.setHorizontalGroup(
            rSPanelBorderGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelBorderGradient1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSPanelImage3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        rSPanelBorderGradient1Layout.setVerticalGroup(
            rSPanelBorderGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelBorderGradient1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rSPanelImage3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        rSPanelBorderGradient2.setBorderBottom(false);
        rSPanelBorderGradient2.setBorderLeft(false);
        rSPanelBorderGradient2.setBorderRight(false);
        rSPanelBorderGradient2.setBorderTop(false);
        rSPanelBorderGradient2.setColorPrimario(new java.awt.Color(255, 255, 255));
        rSPanelBorderGradient2.setColorSecundario(new java.awt.Color(255, 255, 255));

        rSPanelImage4.setImagen(new javax.swing.ImageIcon(getClass().getResource("/imgBotones/lblBanner1.png"))); // NOI18N

        lblCaja5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCaja5.setForeground(new java.awt.Color(51, 51, 51));
        lblCaja5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCaja5.setText("TOTAL VENTAS");

        rSLabelIcon1.setForeground(new java.awt.Color(255, 255, 255));
        rSLabelIcon1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.MONETIZATION_ON);

        labelTotalVentas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelTotalVentas.setForeground(new java.awt.Color(51, 51, 51));
        labelTotalVentas.setText("0.00");

        javax.swing.GroupLayout rSPanelImage4Layout = new javax.swing.GroupLayout(rSPanelImage4);
        rSPanelImage4.setLayout(rSPanelImage4Layout);
        rSPanelImage4Layout.setHorizontalGroup(
            rSPanelImage4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelImage4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(rSLabelIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(262, Short.MAX_VALUE))
            .addGroup(rSPanelImage4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(rSPanelImage4Layout.createSequentialGroup()
                    .addGap(84, 84, 84)
                    .addComponent(lblCaja5, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(99, Short.MAX_VALUE)))
            .addGroup(rSPanelImage4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(rSPanelImage4Layout.createSequentialGroup()
                    .addContainerGap(240, Short.MAX_VALUE)
                    .addComponent(labelTotalVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        rSPanelImage4Layout.setVerticalGroup(
            rSPanelImage4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelImage4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(rSLabelIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(rSPanelImage4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(rSPanelImage4Layout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addComponent(lblCaja5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(18, 18, 18)))
            .addGroup(rSPanelImage4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(rSPanelImage4Layout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addComponent(labelTotalVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(18, 18, 18)))
        );

        javax.swing.GroupLayout rSPanelBorderGradient2Layout = new javax.swing.GroupLayout(rSPanelBorderGradient2);
        rSPanelBorderGradient2.setLayout(rSPanelBorderGradient2Layout);
        rSPanelBorderGradient2Layout.setHorizontalGroup(
            rSPanelBorderGradient2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelBorderGradient2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSPanelImage4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        rSPanelBorderGradient2Layout.setVerticalGroup(
            rSPanelBorderGradient2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelBorderGradient2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rSPanelImage4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        rSPanelBorderGradient3.setBorderBottom(false);
        rSPanelBorderGradient3.setBorderLeft(false);
        rSPanelBorderGradient3.setBorderRight(false);
        rSPanelBorderGradient3.setBorderTop(false);
        rSPanelBorderGradient3.setColorPrimario(new java.awt.Color(255, 255, 255));
        rSPanelBorderGradient3.setColorSecundario(new java.awt.Color(255, 255, 255));

        rSPanelImage5.setImagen(new javax.swing.ImageIcon(getClass().getResource("/imgBotones/lblBanner1.png"))); // NOI18N

        lblCaja6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCaja6.setForeground(new java.awt.Color(51, 51, 51));
        lblCaja6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCaja6.setText("NO. VENTAS");

        rSLabelIcon2.setForeground(new java.awt.Color(255, 255, 255));
        rSLabelIcon2.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CHECK);

        labelNuVentas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelNuVentas.setForeground(new java.awt.Color(51, 51, 51));
        labelNuVentas.setText("0.00");

        javax.swing.GroupLayout rSPanelImage5Layout = new javax.swing.GroupLayout(rSPanelImage5);
        rSPanelImage5.setLayout(rSPanelImage5Layout);
        rSPanelImage5Layout.setHorizontalGroup(
            rSPanelImage5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelImage5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(rSLabelIcon2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(262, Short.MAX_VALUE))
            .addGroup(rSPanelImage5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(rSPanelImage5Layout.createSequentialGroup()
                    .addGap(90, 90, 90)
                    .addComponent(lblCaja6, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(95, Short.MAX_VALUE)))
            .addGroup(rSPanelImage5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(rSPanelImage5Layout.createSequentialGroup()
                    .addContainerGap(234, Short.MAX_VALUE)
                    .addComponent(labelNuVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        rSPanelImage5Layout.setVerticalGroup(
            rSPanelImage5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelImage5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(rSLabelIcon2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(rSPanelImage5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(rSPanelImage5Layout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addComponent(lblCaja6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(18, 18, 18)))
            .addGroup(rSPanelImage5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(rSPanelImage5Layout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addComponent(labelNuVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(18, 18, 18)))
        );

        javax.swing.GroupLayout rSPanelBorderGradient3Layout = new javax.swing.GroupLayout(rSPanelBorderGradient3);
        rSPanelBorderGradient3.setLayout(rSPanelBorderGradient3Layout);
        rSPanelBorderGradient3Layout.setHorizontalGroup(
            rSPanelBorderGradient3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelBorderGradient3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSPanelImage5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        rSPanelBorderGradient3Layout.setVerticalGroup(
            rSPanelBorderGradient3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelBorderGradient3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rSPanelImage5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        rSPanelBorderGradient6.setBorderBottom(false);
        rSPanelBorderGradient6.setBorderLeft(false);
        rSPanelBorderGradient6.setBorderRight(false);
        rSPanelBorderGradient6.setBorderTop(false);
        rSPanelBorderGradient6.setColorPrimario(new java.awt.Color(255, 255, 255));
        rSPanelBorderGradient6.setColorSecundario(new java.awt.Color(255, 255, 255));

        rSPanelImage7.setImagen(new javax.swing.ImageIcon(getClass().getResource("/imgBotones/lblBanner2.png"))); // NOI18N

        lblCaja7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCaja7.setForeground(new java.awt.Color(51, 51, 51));
        lblCaja7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCaja7.setText("COMPRAS");

        rSLabelIcon3.setForeground(new java.awt.Color(255, 255, 255));
        rSLabelIcon3.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SHOPPING_BASKET);

        labelCompras.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelCompras.setForeground(new java.awt.Color(51, 51, 51));
        labelCompras.setText("0.00");

        javax.swing.GroupLayout rSPanelImage7Layout = new javax.swing.GroupLayout(rSPanelImage7);
        rSPanelImage7.setLayout(rSPanelImage7Layout);
        rSPanelImage7Layout.setHorizontalGroup(
            rSPanelImage7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelImage7Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(rSLabelIcon3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(276, Short.MAX_VALUE))
            .addGroup(rSPanelImage7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(rSPanelImage7Layout.createSequentialGroup()
                    .addGap(88, 88, 88)
                    .addComponent(lblCaja7, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(105, Short.MAX_VALUE)))
            .addGroup(rSPanelImage7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(rSPanelImage7Layout.createSequentialGroup()
                    .addContainerGap(236, Short.MAX_VALUE)
                    .addComponent(labelCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        rSPanelImage7Layout.setVerticalGroup(
            rSPanelImage7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelImage7Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(rSLabelIcon3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(rSPanelImage7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(rSPanelImage7Layout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addComponent(lblCaja7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(18, 18, 18)))
            .addGroup(rSPanelImage7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(rSPanelImage7Layout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addComponent(labelCompras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(18, 18, 18)))
        );

        javax.swing.GroupLayout rSPanelBorderGradient6Layout = new javax.swing.GroupLayout(rSPanelBorderGradient6);
        rSPanelBorderGradient6.setLayout(rSPanelBorderGradient6Layout);
        rSPanelBorderGradient6Layout.setHorizontalGroup(
            rSPanelBorderGradient6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelBorderGradient6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSPanelImage7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        rSPanelBorderGradient6Layout.setVerticalGroup(
            rSPanelBorderGradient6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelBorderGradient6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rSPanelImage7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        rSPanelBorderGradient7.setBorderBottom(false);
        rSPanelBorderGradient7.setBorderLeft(false);
        rSPanelBorderGradient7.setBorderRight(false);
        rSPanelBorderGradient7.setBorderTop(false);
        rSPanelBorderGradient7.setColorPrimario(new java.awt.Color(255, 255, 255));
        rSPanelBorderGradient7.setColorSecundario(new java.awt.Color(255, 255, 255));

        rSPanelImage8.setImagen(new javax.swing.ImageIcon(getClass().getResource("/imgBotones/lblBanner2.png"))); // NOI18N

        lblCaja8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCaja8.setForeground(new java.awt.Color(51, 51, 51));
        lblCaja8.setText("PAGOS PENDIENTES");

        rSLabelIcon4.setForeground(new java.awt.Color(255, 255, 255));
        rSLabelIcon4.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.MONEY_OFF);

        labelPagos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelPagos.setForeground(new java.awt.Color(51, 51, 51));
        labelPagos.setText("0.00");

        javax.swing.GroupLayout rSPanelImage8Layout = new javax.swing.GroupLayout(rSPanelImage8);
        rSPanelImage8.setLayout(rSPanelImage8Layout);
        rSPanelImage8Layout.setHorizontalGroup(
            rSPanelImage8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelImage8Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(rSLabelIcon4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(263, Short.MAX_VALUE))
            .addGroup(rSPanelImage8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(rSPanelImage8Layout.createSequentialGroup()
                    .addGap(92, 92, 92)
                    .addComponent(lblCaja8, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(100, Short.MAX_VALUE)))
            .addGroup(rSPanelImage8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(rSPanelImage8Layout.createSequentialGroup()
                    .addContainerGap(235, Short.MAX_VALUE)
                    .addComponent(labelPagos, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        rSPanelImage8Layout.setVerticalGroup(
            rSPanelImage8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelImage8Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(rSLabelIcon4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(rSPanelImage8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(rSPanelImage8Layout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addComponent(lblCaja8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(18, 18, 18)))
            .addGroup(rSPanelImage8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(rSPanelImage8Layout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addComponent(labelPagos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(18, 18, 18)))
        );

        javax.swing.GroupLayout rSPanelBorderGradient7Layout = new javax.swing.GroupLayout(rSPanelBorderGradient7);
        rSPanelBorderGradient7.setLayout(rSPanelBorderGradient7Layout);
        rSPanelBorderGradient7Layout.setHorizontalGroup(
            rSPanelBorderGradient7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelBorderGradient7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSPanelImage8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        rSPanelBorderGradient7Layout.setVerticalGroup(
            rSPanelBorderGradient7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelBorderGradient7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rSPanelImage8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        rSPanelBorderGradient8.setBorderBottom(false);
        rSPanelBorderGradient8.setBorderLeft(false);
        rSPanelBorderGradient8.setBorderRight(false);
        rSPanelBorderGradient8.setBorderTop(false);
        rSPanelBorderGradient8.setColorPrimario(new java.awt.Color(255, 255, 255));
        rSPanelBorderGradient8.setColorSecundario(new java.awt.Color(255, 255, 255));

        rSPanelImage9.setImagen(new javax.swing.ImageIcon(getClass().getResource("/imgBotones/lblBanner2.png"))); // NOI18N

        lblCaja9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCaja9.setForeground(new java.awt.Color(51, 51, 51));
        lblCaja9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCaja9.setText("GANANCIAS");

        rSLabelIcon5.setForeground(new java.awt.Color(255, 255, 255));
        rSLabelIcon5.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.MONETIZATION_ON);

        labelGanancias.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelGanancias.setForeground(new java.awt.Color(51, 51, 51));
        labelGanancias.setText("0.00");

        javax.swing.GroupLayout rSPanelImage9Layout = new javax.swing.GroupLayout(rSPanelImage9);
        rSPanelImage9.setLayout(rSPanelImage9Layout);
        rSPanelImage9Layout.setHorizontalGroup(
            rSPanelImage9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelImage9Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(rSLabelIcon5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(259, Short.MAX_VALUE))
            .addGroup(rSPanelImage9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(rSPanelImage9Layout.createSequentialGroup()
                    .addGap(87, 87, 87)
                    .addComponent(lblCaja9, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(99, Short.MAX_VALUE)))
            .addGroup(rSPanelImage9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(rSPanelImage9Layout.createSequentialGroup()
                    .addContainerGap(233, Short.MAX_VALUE)
                    .addComponent(labelGanancias, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        rSPanelImage9Layout.setVerticalGroup(
            rSPanelImage9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelImage9Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(rSLabelIcon5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(rSPanelImage9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(rSPanelImage9Layout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addComponent(lblCaja9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(18, 18, 18)))
            .addGroup(rSPanelImage9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(rSPanelImage9Layout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addComponent(labelGanancias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(18, 18, 18)))
        );

        javax.swing.GroupLayout rSPanelBorderGradient8Layout = new javax.swing.GroupLayout(rSPanelBorderGradient8);
        rSPanelBorderGradient8.setLayout(rSPanelBorderGradient8Layout);
        rSPanelBorderGradient8Layout.setHorizontalGroup(
            rSPanelBorderGradient8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelBorderGradient8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rSPanelImage9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        rSPanelBorderGradient8Layout.setVerticalGroup(
            rSPanelBorderGradient8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelBorderGradient8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rSPanelImage9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout panelStockMinimoLayout = new javax.swing.GroupLayout(panelStockMinimo);
        panelStockMinimo.setLayout(panelStockMinimoLayout);
        panelStockMinimoLayout.setHorizontalGroup(
            panelStockMinimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelStockMinimoLayout.setVerticalGroup(
            panelStockMinimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 332, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelProductosMasVendidosLayout = new javax.swing.GroupLayout(panelProductosMasVendidos);
        panelProductosMasVendidos.setLayout(panelProductosMasVendidosLayout);
        panelProductosMasVendidosLayout.setHorizontalGroup(
            panelProductosMasVendidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelProductosMasVendidosLayout.setVerticalGroup(
            panelProductosMasVendidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(panelStockMinimo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(panelProductosMasVendidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rSPanelBorderGradient1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rSPanelBorderGradient6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rSPanelBorderGradient7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rSPanelBorderGradient2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rSPanelBorderGradient8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rSPanelBorderGradient3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(rSPanelBorderGradient3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rSPanelBorderGradient2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rSPanelBorderGradient1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(rSPanelBorderGradient8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rSPanelBorderGradient7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rSPanelBorderGradient6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelStockMinimo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelProductosMasVendidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {rSPanelBorderGradient1, rSPanelBorderGradient2, rSPanelBorderGradient3, rSPanelBorderGradient6, rSPanelBorderGradient7, rSPanelBorderGradient8});

        add(jPanel2);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JLabel labelCompras;
    public static javax.swing.JLabel labelGanancias;
    private RSMaterialComponent.RSLabelIcon labelIcon;
    public static javax.swing.JLabel labelNuVentas;
    public static javax.swing.JLabel labelPagos;
    public static javax.swing.JLabel labelProductos;
    public static javax.swing.JLabel labelTotalVentas;
    public static javax.swing.JLabel lblCaja4;
    public static javax.swing.JLabel lblCaja5;
    public static javax.swing.JLabel lblCaja6;
    public static javax.swing.JLabel lblCaja7;
    public static javax.swing.JLabel lblCaja8;
    public static javax.swing.JLabel lblCaja9;
    private javax.swing.JPanel panelProductosMasVendidos;
    private javax.swing.JPanel panelStockMinimo;
    private RSMaterialComponent.RSLabelIcon rSLabelIcon1;
    private RSMaterialComponent.RSLabelIcon rSLabelIcon2;
    private RSMaterialComponent.RSLabelIcon rSLabelIcon3;
    private RSMaterialComponent.RSLabelIcon rSLabelIcon4;
    private RSMaterialComponent.RSLabelIcon rSLabelIcon5;
    private RSMaterialComponent.RSPanelBorderGradient rSPanelBorderGradient1;
    private RSMaterialComponent.RSPanelBorderGradient rSPanelBorderGradient2;
    private RSMaterialComponent.RSPanelBorderGradient rSPanelBorderGradient3;
    private RSMaterialComponent.RSPanelBorderGradient rSPanelBorderGradient6;
    private RSMaterialComponent.RSPanelBorderGradient rSPanelBorderGradient7;
    private RSMaterialComponent.RSPanelBorderGradient rSPanelBorderGradient8;
    private rojeru_san.rspanel.RSPanelImage rSPanelImage3;
    private rojeru_san.rspanel.RSPanelImage rSPanelImage4;
    private rojeru_san.rspanel.RSPanelImage rSPanelImage5;
    private rojeru_san.rspanel.RSPanelImage rSPanelImage7;
    private rojeru_san.rspanel.RSPanelImage rSPanelImage8;
    private rojeru_san.rspanel.RSPanelImage rSPanelImage9;
    // End of variables declaration//GEN-END:variables
}
