package vistaVentas;

import ajustes.PanelListener;
import bo.PagoVentaBO;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.text.DecimalFormat;
import java.util.List;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
import javax.swing.SwingWorker;
import javax.swing.filechooser.FileNameExtensionFilter;
import necesario.RSFileChooser;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import reportes.ExcelGenerator;
import reportes.FakeDataProvider;
import reportes.GeneraReporte;
import rojerusan.RSNotifyFade;
/**
 *
 * @author Kevscl
 */
public class PagosPendientes extends javax.swing.JFrame implements PanelListener {

    /**
     * Creates new form PagosPendientes
     */
    PagoVentaBO pvbo = new PagoVentaBO();

    public PagosPendientes() {
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
        listarPagos();
        jPopupMenu1.add(menu);
    }

    public void onPanelClosed() {
        listar(); // Método para actualizar la lista de empleados
    }

    public void listar() {
        pvbo.listarVentaPago(tbVentas);
    }

    public void listarPagos() {
        pvbo.listarPago(tbVentas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JPanel();
        btnAbonar = new RSMaterialComponent.RSButtonMaterialIconTwo();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        rSLabelTextIcon1 = new RSMaterialComponent.RSLabelTextIcon();
        rSLabelHora1 = new rojeru_san.rsdate.RSLabelHora();
        rSLabelIcon3 = new RSMaterialComponent.RSLabelIcon();
        btnListarPagos = new RSMaterialComponent.RSButtonMaterialIconTwo();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbVentas = new RSMaterialComponent.RSTableMetroCustom();
        listarDescripcion = new RSMaterialComponent.RSButtonMaterialIconTwo();
        btnPDF = new RSMaterialComponent.RSButtonMaterialIconTwo();
        btnExcel = new newscomponents.RSButtonFlat_new();
        txtBusqeuda = new RSMaterialComponent.RSTextFieldIconOne();

        menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAbonar.setBackground(new java.awt.Color(58, 159, 171));
        btnAbonar.setText("PAGAR ABONO (F5)");
        btnAbonar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.FILE_UPLOAD);
        btnAbonar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbonarActionPerformed(evt);
            }
        });
        menu.add(btnAbonar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPopupMenu1.getAccessibleContext().setAccessibleParent(menu);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(58, 159, 171));

        rSLabelTextIcon1.setForeground(new java.awt.Color(255, 255, 255));
        rSLabelTextIcon1.setText("PAGOS PENDIENTES");
        rSLabelTextIcon1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rSLabelTextIcon1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SUPERVISOR_ACCOUNT);

        rSLabelHora1.setForeground(new java.awt.Color(255, 255, 255));

        rSLabelIcon3.setForeground(new java.awt.Color(255, 255, 255));
        rSLabelIcon3.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CLOSE);
        rSLabelIcon3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSLabelIcon3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(rSLabelTextIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(172, 172, 172)
                .addComponent(rSLabelHora1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 437, Short.MAX_VALUE)
                .addComponent(rSLabelIcon3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSLabelTextIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(rSLabelHora1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(rSLabelIcon3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        btnListarPagos.setBackground(new java.awt.Color(58, 159, 171));
        btnListarPagos.setText("LISTAR PAGOS ");
        btnListarPagos.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.EVENT_AVAILABLE);
        btnListarPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarPagosActionPerformed(evt);
            }
        });

        tbVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbVentas.setBackgoundHead(new java.awt.Color(58, 159, 171));
        tbVentas.setBackgoundHover(new java.awt.Color(58, 159, 171));
        tbVentas.setSelectionBackground(new java.awt.Color(58, 159, 171));
        tbVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbVentasMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbVentas);

        listarDescripcion.setBackground(new java.awt.Color(58, 159, 171));
        listarDescripcion.setText("LISTAR DESCRIPCIÓN ");
        listarDescripcion.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.EVENT_AVAILABLE);
        listarDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarDescripcionActionPerformed(evt);
            }
        });

        btnPDF.setBackground(new java.awt.Color(58, 159, 171));
        btnPDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reportes/btnExcel.png"))); // NOI18N
        btnPDF.setBorderPainted(false);
        btnPDF.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.PRINT);
        btnPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPDFActionPerformed(evt);
            }
        });

        btnExcel.setBackground(new java.awt.Color(58, 159, 171));
        btnExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reportes/btnExcel.png"))); // NOI18N
        btnExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcelActionPerformed(evt);
            }
        });

        txtBusqeuda.setForeground(new java.awt.Color(58, 159, 171));
        txtBusqeuda.setBorderColor(new java.awt.Color(58, 159, 171));
        txtBusqeuda.setColorIcon(new java.awt.Color(58, 159, 171));
        txtBusqeuda.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        txtBusqeuda.setPlaceholder("BUSCAR");
        txtBusqeuda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBusqeudaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(txtBusqeuda, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btnListarPagos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(listarDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPDF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnListarPagos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(listarDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtBusqeuda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 543));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbVentasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbVentasMouseReleased
        if (evt.isPopupTrigger()) {
            // Obtener la fila seleccionada
            int fila = tbVentas.getSelectedRow();
            // Verificar si se ha seleccionado una fila
            if (fila != -1) {
                // Mostrar el JPopupMenu en la posición del clic
                jPopupMenu1.show(evt.getComponent(), evt.getX(), evt.getY());
            } else {
                //listar();
                jPopupMenu1.setVisible(false);
            }
        }
    }//GEN-LAST:event_tbVentasMouseReleased

    private void rSLabelIcon3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSLabelIcon3MouseClicked
        dispose();
    }//GEN-LAST:event_rSLabelIcon3MouseClicked

    private void btnListarPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarPagosActionPerformed
        listarPagos();
    }//GEN-LAST:event_btnListarPagosActionPerformed

    private void listarDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarDescripcionActionPerformed
        listar();
    }//GEN-LAST:event_listarDescripcionActionPerformed

    private void btnAbonarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbonarActionPerformed
        int fila = tbVentas.getSelectedRow();
        if (fila != -1) {
            AbonarPago c = new AbonarPago();
            float total = Float.parseFloat(tbVentas.getValueAt(fila, 6).toString());
            float abono = Float.parseFloat(tbVentas.getValueAt(fila, 7).toString());
            float resto = total - abono;

            // Formatear los valores a dos decimales
            DecimalFormat decimalFormat = new DecimalFormat("#.00");
            total = Float.parseFloat(decimalFormat.format(total));
            abono = Float.parseFloat(decimalFormat.format(abono));
            resto = Float.parseFloat(decimalFormat.format(resto));

            c.txtPendiente.setText(decimalFormat.format(resto));
            c.labelIDDevo.setText(tbVentas.getValueAt(fila, 0).toString());
            c.txtCliente.setText(tbVentas.getValueAt(fila, 3).toString());

            // Asignar el valor seleccionado en el campo comboGenero
            c.setAlwaysOnTop(true); // Mantener la ventana emergente en la capa superior
            c.setPanelListener(this);
            c.setVisible(true);

            tbVentas.clearSelection();
            jPopupMenu1.setVisible(false);
        } else {
            listar();
        }
    }//GEN-LAST:event_btnAbonarActionPerformed

    private void btnPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPDFActionPerformed
        pdf();
    }//GEN-LAST:event_btnPDFActionPerformed

    private void btnExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcelActionPerformed
        exportar();
    }//GEN-LAST:event_btnExcelActionPerformed

    private void txtBusqeudaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusqeudaKeyReleased
        pvbo.listarVentaPagoBusqueda(tbVentas, txtBusqeuda.getText());
    }//GEN-LAST:event_txtBusqeudaKeyReleased

    public void pdf() {
        String tableName = "Reporte de ventas"; // Cambiar por el nombre de la tabla o vista que deseas mostrar
        String description = "Listado de pagos pendientes"; // Cambiar por una descripción adecuada

        RSFileChooser fileChooser = new RSFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos PDF (*.pdf)", "pdf");
        fileChooser.setAcceptAllFileFilterUsed(false);
        fileChooser.setFileFilter(filter);
        fileChooser.setDialogTitle("GUARDAR ARCHIVO");
        if (fileChooser.showSaveDialog(null) == RSFileChooser.APPROVE_OPTION) {
            String filePath = fileChooser.getSelectedFile().getAbsolutePath();
            if (!filePath.toLowerCase().endsWith(".pdf")) {
                filePath += ".pdf"; // Agrega extensión .pdf si no está presente
            }
            GeneraReporte g = new GeneraReporte();
            String mensaje = g.generaPDFTabla(tableName, description, filePath, tbVentas);
            if (!mensaje.equals("PDF GENERADO")) {
                new rojerusan.RSNotifyFade("¡ERROR!", "¡Error al generar PDF!", 3, RSNotifyFade.PositionNotify.BottomRight, RSNotifyFade.TypeNotify.WARNING).setVisible(true);
            } else {
                new rojerusan.RSNotifyFade("¡SUCCESS!", "¡PDF Generado exitosamente!", 3, RSNotifyFade.PositionNotify.BottomRight, RSNotifyFade.TypeNotify.SUCCESS).setVisible(true);
            }
        }
    }

    public void exportar() {
        List<String> headers = FakeDataProvider.getTableHeaders(tbVentas);
        int tam = tbVentas.getRowCount();
        List<List<String>> content = FakeDataProvider.getTableContent(tbVentas, tam); // Obtén los datos de las primeras 20 filas

        ExcelGenerator excelGenerator = new ExcelGenerator();
        HSSFWorkbook workbook = excelGenerator.generateExcel("PERSONAS", headers, content);

        RSFileChooser fileChooser = new RSFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos Excel (*.xls)", "xls");
        fileChooser.setAcceptAllFileFilterUsed(false);
        fileChooser.setFileFilter(filter);
        fileChooser.setDialogTitle("GUARDAR ARCHIVO");
        if (fileChooser.showSaveDialog(this) == RSFileChooser.APPROVE_OPTION) {
            System.out.println(fileChooser.getSelectedFile().getAbsolutePath());

            File archivo = new File(fileChooser.getSelectedFile().getAbsolutePath());

            SwingWorker<Void, Void> worker = new SwingWorker<Void, Void>() {
                @Override
                protected Void doInBackground() throws Exception {
                    try {
                        OutputStream out = null;
                        if (getFileExtension(archivo)) {
                            out = new FileOutputStream(fileChooser.getSelectedFile().getAbsolutePath());
                        } else {
                            out = new FileOutputStream(fileChooser.getSelectedFile().getAbsolutePath() + ".xls");
                        }
                        workbook.write(out);
                        workbook.close();
                        out.flush();
                        out.close();
                    } catch (FileNotFoundException ex) {
                        showErrorAlert("Algo salió mal. El archivo que intenta sobreescribir se encuentra abierto, cierre el archivo e inténtelo de nuevo.");
                    } catch (IOException ex) {
                        showErrorAlert("Algo salió mal. No fue posible generar el archivo.");
                    }
                    return null;
                }

                @Override
                protected void done() {
                    showSuccessAlert("Archivo guardado con éxito.");
                }
            };
            worker.execute();
        }

    }

    private void showErrorAlert(String mensaje) {
        new rojerusan.RSNotifyFade("¡ERROR!", "¡" + mensaje + "!", 3, RSNotifyFade.PositionNotify.BottomRight, RSNotifyFade.TypeNotify.WARNING).setVisible(true);

    }

    // Método para mostrar un cuadro de diálogo de éxito
    private void showSuccessAlert(String mensaje) {
        new rojerusan.RSNotifyFade("¡SUCCESS!", "¡" + mensaje + "!", 5, RSNotifyFade.PositionNotify.BottomRight, RSNotifyFade.TypeNotify.SUCCESS).setVisible(true);
    }

    private boolean getFileExtension(File file) {
        String ext = null;
        String s = file.getName();
        int i = s.lastIndexOf('.');

        if (i > 0 && i < s.length() - 1) {
            ext = s.substring(i + 1).toLowerCase();
        }

        if (ext != null) {
            return true;
        } else {
            return false;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PagosPendientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PagosPendientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PagosPendientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PagosPendientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PagosPendientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonMaterialIconTwo btnAbonar;
    private newscomponents.RSButtonFlat_new btnExcel;
    private RSMaterialComponent.RSButtonMaterialIconTwo btnListarPagos;
    private RSMaterialComponent.RSButtonMaterialIconTwo btnPDF;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private RSMaterialComponent.RSButtonMaterialIconTwo listarDescripcion;
    private javax.swing.JPanel menu;
    private rojeru_san.rsdate.RSLabelHora rSLabelHora1;
    private RSMaterialComponent.RSLabelIcon rSLabelIcon3;
    private RSMaterialComponent.RSLabelTextIcon rSLabelTextIcon1;
    private RSMaterialComponent.RSTableMetroCustom tbVentas;
    private RSMaterialComponent.RSTextFieldIconOne txtBusqeuda;
    // End of variables declaration//GEN-END:variables

}
