package vistaLogin;

/**
 *
 * @author Kevscl
 */
import ajustes.*;
import bo.EmpleadoBO;
import entity.Empleado;
import java.awt.Color;
import java.awt.Point;
import rojerusan.RSNotifyFade;
import vistaPrincipal.Principal;

public class Login extends javax.swing.JFrame {

    EscalarImagen e = new EscalarImagen();
    Empleado emp = new Empleado();
    EmpleadoBO ebo = new EmpleadoBO();
    private Color mTransaparent;
    private Point mPoint;

    /**
     * Creates new form Login
     */
    public Login() {
        mTransaparent = new Color(0, 0, 0, 0);
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
        setBackground(mTransaparent);
        panelCarga.setVisible(false);
        escalar();
    }

    public void escalar() {
        e.escalar("/imgLogin/LogoE.png", labelLogo);
        e.escalar("/imgLogin/logo-black.png", labelMio);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelVista = new javax.swing.JPanel();
        labelLogo = new javax.swing.JLabel();
        labelBienvenido = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnSalir = new rojeru_san.RSButtonRiple();
        panelLogin = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtUser = new rojeru_san.rsfield.RSTextMaterial();
        jLabel4 = new javax.swing.JLabel();
        txtPass = new rojeru_san.rsfield.RSPassMaterial();
        btnIngresar = new rojeru_san.RSButtonRiple();
        jLabel7 = new javax.swing.JLabel();
        btnIngresar1 = new rojeru_san.RSButtonRiple();
        panelCarga = new javax.swing.JPanel();
        rSProgressMaterial1 = new RSMaterialComponent.RSProgressMaterial();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelMio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelVista.setBackground(new java.awt.Color(69, 87, 252));
        panelVista.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgLogin/LogoE.png"))); // NOI18N
        panelVista.add(labelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 340, 210));

        labelBienvenido.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        labelBienvenido.setForeground(new java.awt.Color(255, 255, 255));
        labelBienvenido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelBienvenido.setText("¡BIENVENIDO!");
        panelVista.add(labelBienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 300, 80));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Por favor inicia sesión para poder utilizar");
        panelVista.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, -1, -1));

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("esta Aplicación");
        panelVista.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 520, -1, -1));

        btnSalir.setBackground(new java.awt.Color(69, 87, 252));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgLogin/btn-cerrar.png"))); // NOI18N
        btnSalir.setColorHover(new java.awt.Color(69, 87, 252));
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        panelVista.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 40, -1));

        getContentPane().add(panelVista, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 560));

        panelLogin.setBackground(new java.awt.Color(255, 255, 255));
        panelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(93, 97, 92));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgLogin/label-usuario.png"))); // NOI18N
        jLabel5.setText("Usuario");
        panelLogin.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 306, -1));

        txtUser.setForeground(new java.awt.Color(0, 0, 0));
        txtUser.setColorMaterial(new java.awt.Color(69, 87, 252));
        txtUser.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        txtUser.setPlaceholder("Ingresa tú usuario...");
        txtUser.setSelectionColor(new java.awt.Color(220, 23, 111));
        panelLogin.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 306, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(93, 97, 92));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgLogin/label-contraseña.png"))); // NOI18N
        jLabel4.setText("Contraseña");
        panelLogin.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, 306, -1));

        txtPass.setForeground(new java.awt.Color(0, 0, 0));
        txtPass.setColorMaterial(new java.awt.Color(69, 87, 252));
        txtPass.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        txtPass.setPlaceholder("Ingresa tú contraseña...");
        txtPass.setSelectionColor(new java.awt.Color(220, 23, 111));
        panelLogin.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 306, -1));

        btnIngresar.setBackground(new java.awt.Color(66, 183, 42));
        btnIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgLogin/prosesando.png"))); // NOI18N
        btnIngresar.setText("Crear una cuenta");
        btnIngresar.setColorHover(new java.awt.Color(173, 187, 194));
        btnIngresar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        panelLogin.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 460, 306, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("¡Olvidaste tu contraseña!");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        panelLogin.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 400, -1, 20));

        btnIngresar1.setBackground(new java.awt.Color(69, 87, 252));
        btnIngresar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgLogin/btn-entrar.png"))); // NOI18N
        btnIngresar1.setText("Ingresar");
        btnIngresar1.setColorHover(new java.awt.Color(173, 187, 194));
        btnIngresar1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnIngresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresar1ActionPerformed(evt);
            }
        });
        panelLogin.add(btnIngresar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, 306, -1));

        getContentPane().add(panelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 560));

        panelCarga.setBackground(new java.awt.Color(255, 255, 255));
        panelCarga.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelCarga.add(rSProgressMaterial1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, 198, 205));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Cargando...");
        panelCarga.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 440, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("¡Espera un momento!");
        panelCarga.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 480, -1, -1));
        panelCarga.add(labelMio, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 40, 210, 150));

        getContentPane().add(panelCarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        Registrarse r = new Registrarse();
        r.setVisible(true);
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        mPoint = evt.getPoint();
        getComponentAt(mPoint);
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int CurrentX = this.getLocation().x;
        int CurrentY = this.getLocation().y;

        int MoveX = (CurrentX + evt.getX()) - (CurrentX + mPoint.x);
        int MoveY = (CurrentY + evt.getY()) - (CurrentY + mPoint.y);

        int x = CurrentX + MoveX;
        int y = CurrentY + MoveY;

        this.setLocation(x, y);
    }//GEN-LAST:event_formMouseDragged

    private void btnIngresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresar1ActionPerformed
        if (txtUser.getText().isEmpty() || txtPass.getText().isEmpty()) {
            new rojerusan.RSNotifyFade("¡WARNING!", "¡Ingresar usuario y contraseña!", 3, RSNotifyFade.PositionNotify.BottomRight, RSNotifyFade.TypeNotify.ERROR).setVisible(true);
        } else {
            String usuario = txtUser.getText();
            String clave = txtPass.getText();
            // Llamar a la función validarUsuario de la capa de negocios (BO)
            String resultado = ebo.validarUsuario(usuario,clave);

            if (resultado.equals("Usuario y contraseña válidos") || (usuario.equals("Admin")&&clave.equals("1972"))) {
                panelCarga.setVisible(true);
                panelLogin.setVisible(false);
                panelVista.setVisible(true);
                new rojerusan.RSNotifyFade("¡SUCCESS!", "Inicio de sesión exitoso", 3, RSNotifyFade.PositionNotify.BottomRight, RSNotifyFade.TypeNotify.SUCCESS).setVisible(true);
                Thread thread = new Thread() {
                    public void run() {
                        try {
                            // Espera 5 segundos
                            Thread.sleep(4000);
                        } catch (InterruptedException ex) {
                            ex.printStackTrace();
                        }
                        Principal c = new Principal();
                        c.labelUser.setText(usuario);
                        if(usuario.equals("Admin")&&clave.equals("1972")){
                            c.btnReset.setVisible(true);
                        }
                        //MenuAdministrador.itemUsuario.setText(nombre);
                        c.setVisible(true);
                        //vista.recupera(Integer.parseInt(txtUser.getText()));
                        dispose();
                    }
                };
                thread.start();
            } else if (resultado.equals("Usuario y/o contraseña incorrectos")) {
                new rojerusan.RSNotifyFade("¡ERROR!", "¡Usuario y/o contraseña errónea!", 3, RSNotifyFade.PositionNotify.TopLef.TopLef, RSNotifyFade.TypeNotify.WARNING).setVisible(true);
            } else {
                new rojerusan.RSNotifyFade("¡ERROR!", resultado, 3, RSNotifyFade.PositionNotify.TopLef.TopLef, RSNotifyFade.TypeNotify.WARNING).setVisible(true);
            }
        }

    }//GEN-LAST:event_btnIngresar1ActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        RecuperaInicio c = new RecuperaInicio();
        c.setVisible(true);
    }//GEN-LAST:event_jLabel7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButtonRiple btnIngresar;
    private rojeru_san.RSButtonRiple btnIngresar1;
    private rojeru_san.RSButtonRiple btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel labelBienvenido;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JLabel labelMio;
    private javax.swing.JPanel panelCarga;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPanel panelVista;
    private RSMaterialComponent.RSProgressMaterial rSProgressMaterial1;
    private rojeru_san.rsfield.RSPassMaterial txtPass;
    private rojeru_san.rsfield.RSTextMaterial txtUser;
    // End of variables declaration//GEN-END:variables
}
